config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show]#, path_names: {index: "usuarios", show: ":id"}
  get '/usuario/:name', to: redirect('/usuario/%{name}')

  get '/perfil', to: 'users#perfil'
  
  root 'static_pages#home'
  get '/blog', to: 'static_pages#blog'
  get '/servicios', to: 'static_pages#services'
  get '/contacto', to: 'static_pages#contact'
  get '/biografia', to: 'static_pages#biography'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :trackable, :validatable

	def full_name
		
		if self.username.blank?
			self.email
		else
			self.username
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	
	before_filter :configure_permitted_parameters, if: :devise_controller?

	protected

		def configure_permitted_parameters
			devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password) }
			devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :name, :email, :password, :current_password, :sex, :date_of_birth, :description, :contact, :webpage, :webtitle) }
		end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end
	def blog
	end
	def services
	end
	def contact
		@users = User.all
	end
	def biography
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end
	def show
		@users = User.all
		@user = User.find(params[:id])
	end
	#def perfil
	#	if user_signed_in?
	#		@users = User.all
	#		@user = User.find(current_user)
	#	else
	#		redirect_to user_session_url
	#		flash[:info] = "Inicia sesión para ver esa información"
	#	end
	#end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alerts.html.erb
<% flash.each do |key, value| %>
	<script>
		$.notify("<%= value %>", "<%= key %>");
	</script>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
	&copy; Copyright 2016
</footer>

app/views/layouts/_navbar.html.erb
<% x = request.fullpath %>
<% if x == "/perfil" or x == "/users/edit" or x >= "/users/0" %>
	<nav class="navbar">
		<%= link_to "Conected", root_path, class: 'navbar-brand' %>

		<ul class="navigation">
			<li><%= link_to 'Inicio', root_path %></li>
			<li><%= link_to 'Usuarios', users_path %></li>
			<% if current_user %>
				<li><%= link_to 'Perfil', perfil_path %></li>
				<li><%= link_to 'Editar Perfil', edit_user_registration_path %></li>
				<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
			<% else %>
			<li><%= link_to 'Login', new_user_session_path %></li>
			<% end %>
		</ul>
	</nav>
<% else %>
	<nav class="navbar">
		<%= link_to "Conected", root_path, class: 'navbar-brand' %>

		<ul class="navigation">
			<li><%= link_to 'Inicio', root_path %></li>
			<li><%= link_to 'Blog', blog_path %></li>
			<li><%= link_to 'Servicios', servicios_path %></li>
			<li><%= link_to 'Contacto', contacto_path %></li>
			<li><%= link_to 'Biografía', biografia_path %></li>
			<li><%= link_to 'Usuarios', users_path %></li>
			<% if current_user %>
				<li><%= link_to 'Perfil', perfil_path %></li>
				<li><%= link_to 'Editar Perfil', edit_user_registration_path %></li>
				<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
			<% else %>
			<li><%= link_to 'Login', new_user_session_path %></li>
			<% end %>
		</ul>
	</nav>
<% end %>

app/views/layouts/_userinfo.html.erb
<% unless @user.name.blank? %>
	<li>Nombre: <%= @user.name %></li>
<% end %>

<% if current_user %> Bienvenido
	<% if @user.username? %>
		<%= @user.username %>
	<% else %>
		<%= @user.email %>
	<% end %>
	<br>
	Nombre: <%= @user.name %> <br>
	Fecha de nacimiento: <%= @user.date_of_birth %> <br>
	<% case @user.sex %>
		<% when 1 %>
			Sexo: Hombre
		<% when 2 %>
			Sexo: Mujer
		<% else %>
			Sexo: Sin especificar
	<% end %><br>
	Descripción: <%= @user.description %> <br>
	Información de Contacto: <a href="mailto:<%= @user.contact %>"><%= @user.contact %> </a> <br>
	Página Web: <%= link_to @user.webtitle, @user.webpage %><br>
	<!--
	Contraseña encriptada: <%= @user.encrypted_password %> <br>
	Fecha de creación: <%= @user.remember_created_at %> <br>
	Conteo de Inicio de Sesión: <%= @user.sign_in_count %> <br>
	Actual Inicio de Sesión: <%= @user.current_sign_in_at %> <br>
	Último Inicio de Sesión: <%= @user.last_sign_in_at %> <br>
	Actual Dirección IP: <%= @user.current_sign_in_ip %> <br>
	Última Dirección IP: <%= @user.last_sign_in_ip %> <br>-->
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
	<title>Blog</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<script src="https://github.com/notifyjs/notifyjs/blob/master/dist/notify.js"></script>
</head>
<body onload="notify()">
<div class="header"><%= render 'layouts/navbar' %></div>
<div class="alerts"><%= render 'layouts/alerts' %></div>

<div class="container">
	<%= yield %>
</div>

<div class="footer"><%= render 'layouts/footer' %></div>

</body>
</html>

app/views/static_pages/home.html.erb
<h1>Landing Page</h1>
<%= image_tag 'Wallpaper1.jpg' %>
<%= image_tag 'Wallpaper1.png' %>
<h1>Servicios</h1>
<%= image_tag 'Wallpaper2.jpg' %>
<h1>Suscríbete</h1>
<%= image_tag 'mujer.jpg' %>

app/views/users/index.html.erb
<ul>
	<% @users.find_each do |user| %>
		<li><%= link_to user.full_name, user_path(user) %></li>
		<hr>
	<% end %>
</ul>

app/views/users/perfil.html.erb
<h1><%= @user.full_name %></h1>
<ul>
	<%= content_tag(:li, ("Nombre: " + @user.name)) unless @user.name.blank? %>
    <%= content_tag(:li, ("Contacto: " + @user.contact)) unless @user.contact.blank? %>
    <% case @user.sex %>
		<% when 1 %>
			Sexo: Hombre
		<% when 2 %>
			Sexo: Mujer
		<% else %>
			Sexo: Sin especificar
	<% end %><br>
    <%= content_tag(:li, ("Descripción: " + @user.description)) unless @user.description.blank? %>
    <%= content_tag(:li, ("Edad: " + distance_of_time_in_words(Time.now, @user.date_of_birth))) unless @user.date_of_birth.blank? %>
    <% unless @user.webpage.blank? %>
	    <% unless @user.webtitle.blank? %>
	        <li>Página Web: <%= link_to @user.webtitle, @user.webpage %></li>
	    <% end %>
    <% end %>
    <hr>
</ul>

<header>
	<p><% x = request.original_url %></p>
	<p><%= x %></p>
	<p><%= request.original_fullpath %></p>
	<p><%= request.fullpath %></p>
</header>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<ul>
	<%= render 'layouts/userinfo' %>
</ul>